services:
  bibliotheca:
    build: .
    ports:
      - "5054:5054"
    volumes:
      # Mount local data directory for migration support and Kuzu database
      - ./data:/app/data
      # Mount static directory for CSS, JS, and other static files
      - ./app/static:/app/static
    environment:
      # Security - MUST be set via .env file or environment
      - SECRET_KEY=${SECRET_KEY}
      - SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
      
      # Database configuration - KuzuDB
      - KUZU_DB_PATH=/app/data/kuzu
      - GRAPH_DATABASE_ENABLED=true
      
      # Application settings
      - TIMEZONE=${TIMEZONE:-UTC}
      # CRITICAL: Use single worker for KuzuDB compatibility
      - WORKERS=1
      
      # Logging settings - disable verbose initialization to prevent duplicate messages
      - BIBLIOTHECA_VERBOSE_INIT=${BIBLIOTHECA_VERBOSE_INIT:-false}
      
      # Migration settings (DISABLED for manual migration)
      - AUTO_MIGRATE=false
      # - MIGRATION_DEFAULT_USER=admin
    restart: unless-stopped
