services:
  bibliotheca:
    build: .
    ports:
      - "5054:5054"
    volumes:
      # Mount local data directory for migration support, Kuzu database, and backups
      - ./data:/app/data
  # NOTE: Do NOT bind-mount the static directory on macOS.
  # Docker Desktop's osxfs can trigger EDEADLK (Resource deadlock avoided)
  # when Gunicorn/Flask read static files via wsgi.file_wrapper.
  # Static assets are copied into the image at build time; hot-reload of
  # static files should be done with the dev compose file instead.
    environment:
      # Security - MUST be set via .env file or environment
      SECRET_KEY: ${SECRET_KEY}
      SECURITY_PASSWORD_SALT: ${SECURITY_PASSWORD_SALT}

      # Database configuration - KuzuDB
      KUZU_DB_PATH: /app/data/kuzu
      GRAPH_DATABASE_ENABLED: "true"

      # Application settings
      SITE_NAME: ${SITE_NAME:-MyBibliotheca}
      TIMEZONE: ${TIMEZONE:-UTC}
      # CRITICAL: Use single worker for KuzuDB compatibility
      WORKERS: "1"
      # Central log level (controls Gunicorn and Flask loggers)
      LOG_LEVEL: ${LOG_LEVEL}

      # Logging settings - disable verbose initialization to prevent duplicate messages
      MYBIBLIOTHECA_VERBOSE_INIT: ${MYBIBLIOTHECA_VERBOSE_INIT:-false}

  # Kuzu recovery options (uncomment as needed)
  # KUZU_AUTO_RECOVER_CLEAR: "true"   # Full backup + wipe on detected corruption
  # KUZU_DISABLE_AUTO_RENAME_CORRUPT: "true"  # Disable soft auto-rename fallback

      # Migration settings (DISABLED for manual migration)
      AUTO_MIGRATE: "false"
      # - MIGRATION_DEFAULT_USER=admin
    restart: unless-stopped
